POST http://localhost:3001/api/notes 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluQGFwcC5jb20iLCJpZCI6IjY2NjI5NzdhZTNjZmZjMjFlYzQ4YTI1MCIsImlhdCI6MTcxNzczOTIzMH0.Nc_sk8WH-LmqMirZMDX6wjldSElTDJ1Hewb2LHaNaek

{
    "content":"A world of great possibilities can be Achieved with great Software Technology",
    "important":true
}